spring.application.name=pulsepay
# Database Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/pulsepay_db
spring.datasource.username=pulsepay_user
spring.datasource.password=${DB_PASSWORD}

# JPA / Hibernate Settings
# 'update' tells Hibernate to automatically create/update your tables based on your Java code
spring.jpa.hibernate.ddl-auto=update
# This prints the SQL queries to the console so you can see what's happening (great for learning!)
spring.jpa.show-sql=true
# Format the SQL in the console so it's readable
spring.jpa.properties.hibernate.format_sql=true